# Generated by Django 4.2.9 on 2026-02-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True, default="fas fa-box", max_length=50, verbose_name="icon"
            ),
        ),
    ]
